Update python-coding-style-check.yml

diff --git a/.github/workflows/python-coding-style-check.yml b/.github/workflows/python-coding-style-check.yml
--- a/.github/workflows/python-coding-style-check.yml
+++ b/.github/workflows/python-coding-style-check.yml
@@ -13,6 +13,8 @@ on:
 jobs:
   check_files:
     runs-on: ubuntu-latest
+    outputs:
+      changed_files: ${{ steps.changed_files.outputs.changed_files }}
     steps:
       - uses: actions/checkout@v4
       - name: List Changed Python Files
@@ -26,24 +28,31 @@ jobs:
   run_formatter:
     needs: check_files
     runs-on: ubuntu-latest
-    steps:        
+    if: needs.check_files.outputs.changed_files != ''
+    steps:
+      - uses: actions/checkout@v4
+      - name: List Changed Python Files
+        run: |
+          git fetch origin ${{ github.event.pull_request.base.sha }}
+          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.py$' || true)
+          # changed_files=$(git diff --name-only master... | grep '\.py$' || true)
+          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
+        id: changed_files
       - uses: actions/setup-python@v4
         with:
           python-version: '3.9'
+          cache: 'pip'
       - name: Install dependencies
         run: |
           pip3 install -q -U pip
           pip3 install -q poetry
           poetry install
-        if: steps.changed_files.outputs.changed_files != ''
-      - name: Print Message
+      - name: Print hint message
         run: |
-          echo "How to fix CI failures"
+          echo "### How to fix CI failures ###"
           echo "poetry run black       ${{ steps.changed_files.outputs.changed_files }}"
           echo "poetry run ruff --fix  ${{ steps.changed_files.outputs.changed_files }}"
-        if: steps.changed_files.outputs.changed_files != ''
       - name: Run black and ruff
         run: |
           poetry run black --check --diff "${{ steps.changed_files.outputs.changed_files }}"
           poetry run ruff check           "${{ steps.changed_files.outputs.changed_files }}"
-        if: steps.changed_files.outputs.changed_files != ''
